name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        id: beam
        with:
          version-type: strict
          version-file: .tool-versions
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: https://npm.intility.com
          cache: npm
          cache-dependency-path: "**/package-lock.json"
      - name: Install Node dependencies
        run: npm ci
        working-directory: assets
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_INTILITY_COM_TOKEN }}
      - name: Install dependencies
        uses: team-alembic/staple-actions/actions/mix-deps-get@main
      - name: Generate Phoenix components
        uses: team-alembic/staple-actions/actions/mix-task@main
        with:
          mix-env: test
          task: phx_fontawesome.generate
      - name: Run test suite
        uses: team-alembic/staple-actions/actions/mix-task@main
        with:
          mix-env: test
          task: test
